[workspace]
authors = ["ryan_wslhp <ryan_9809@yahoo.com>"]
channels = ["conda-forge"]
name = "GFD_in_Dedalus_book"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
OMP_NUM_THREADS = "1"
NUMEXPR_MAX_THREADS = "1"

[tasks]

[dependencies]
numpy = ">=2.3.0,<3"
cmocean = ">=4.0.3,<5"
dedalus = ">=3.0.3,<4"
pip = ">=25.1.1,<26"
jupyterlab = ">=4.4.3,<5"
jupyter-book = ">=1.0.4.post1,<2"
ghp-import = ">=2.1.0,<3"
